[versions]
agp = "8.9.1"
coilCompose = "2.4.0"
converterGson = "2.9.0"
core = "4.6.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
loggingInterceptor = "4.9.0"
material = "1.12.0"
navigationCompose = "2.8.9"
persistentcookiejar = "v1.0.1"
retrofit = "2.9.0"
nav = "2.8.9"
gson = "2.9.0"
coil = "2.4.0"
cookiejar = "1.0.1"
markwon = "4.6.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
#core = { module = "io.noties.markwon:core", version.ref = "core" }
#ext-latex = { module = "io.noties.markwon:ext-latex", version.ref = "core" }
#ext-latex-jlatexmath = { module = "io.noties.markwon:ext-latex-jlatexmath", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
persistentcookiejar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentcookiejar" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
#markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
## the LaTeX plugin
#markwon-ext-latex = { group = "io.noties.markwon", name = "ext-latex", version.ref = "markwon" }
## the inline-parser plugin
#markwon-inline-parser = { group = "io.noties.markwon", name = "inline-parser", version.ref = "markwon" }
## the linkify plugin
#markwon-linkify = { group = "io.noties.markwon", name = "linkify", version.ref = "markwon" }
## if you need the JLatexMath‐specific artifact:
#markwon-ext-latex-jlatexmath = { group = "io.noties.markwon", name = "ext-latex-jlatexmath", version.ref = "markwon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }